# Mean vs Median: Let’s explore Kirk & Spock of Stats Trek
https://medium.com/chi-squared/mean-vs-median-lets-explore-kirk-spock-of-stats-trek-964a0809167c

In [1]:
import numpy as np

In [2]:
np.random.seed(100)

In [3]:
# Random income of 11 people
incomes = np.random.randint(10, 101, (1,11))
incomes

array([[18, 34, 77, 97, 89, 58, 20, 62, 63, 76, 24]])

In [4]:
# Per Capita Income
np.mean(incomes)

56.18181818181818

In [5]:
# Replace largest value with an outlier
incomes_with_outlier = np.where(incomes == incomes.max(), 100000, incomes)
incomes_with_outlier

array([[    18,     34,     77, 100000,     89,     58,     20,     62,
            63,     76,     24]])

In [6]:
# Per Capita Income
np.mean(incomes_with_outlier)

9138.272727272728

In [7]:
# Median income without outlier
np.median(incomes)

62.0

In [8]:
# Median income with outlier
np.median(incomes_with_outlier)

62.0

In [9]:
sorted_incomes = np.sort(incomes)
sorted_incomes

array([[18, 20, 24, 34, 58, 62, 63, 76, 77, 89, 97]])

In [10]:
sorted_incomes[0,5]

62

In [11]:
sorted_incomes_with_outliers = np.sort(incomes_with_outlier)
sorted_incomes_with_outliers

array([[    18,     20,     24,     34,     58,     62,     63,     76,
            77,     89, 100000]])

In [12]:
sorted_incomes_with_outliers[0,5]

62